<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>msgs</name>
  <version>0.0.0</version>
  <description>Custom message definitions for AUVC</description>
  <maintainer email="nthrasher92973@gmail.com">ngt</maintainer>
  <maintainer email="zarifismatahmed@gmail.com">zarif</maintainer>
  <maintainer email="eshansway@gmail.com">eshan</maintainer>
  <maintainer email="sharel33@yahoo.com">sharel</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <exec_depend>rosidl_default_runtime</exec_depend>

  <depend>std_msgs</depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
