<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>bringup</name>
  <version>0.0.0</version>
  <description>Launch files and configuration for all AUVC subsystems</description>
  <maintainer email="nthrasher92973@gmail.com">ngt</maintainer>
  <maintainer email="zarifismatahmed@gmail.com">zarif</maintainer>
  <maintainer email="eshansway@gmail.com">eshan</maintainer>
  <maintainer email="sharel33@yahoo.com">sharel</maintainer>
  <license>TODO: License declaration</license>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <depend>mavlink</depend>
  <depend>rclpy</depend>
  <depend>mavros_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>python3-gi</depend>
  <depend>python3-gst-1.0</depend>
  <depend>gir1.2-gstreamer-1.0</depend>
  <depend>gstreamer1.0-plugins-good</depend>
  <depend>gstreamer1.0-plugins-bad</depend>
  <depend>gstreamer1.0-libav</depend>
  <depend>ros_gz_bridge</depend>
  <depend>cv_bridge</depend>
  <depend>dt_apriltags</depend>

  <exec_depend>ros2launch</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
